GET http://localhost:3001/bulletins/H1X5IFqg50o9NbnepXouY/visitors
Content-Type: application/json

###

POST http://localhost:3001/bulletins/H1X5IFqg50o9NbnepXouY/visitors
Content-Type: application/json

{
  "name": "Brichi"
}

###

PATCH http://localhost:3001/bulletins/H1X5IFqg50o9NbnepXouY/visitors/5LRVvbDTF5gJb757KIm5g
Content-Type: application/json

{
  "name": "Jiayi"
}

###

DELETE http://localhost:3001/bulletins/H1X5IFqg50o9NbnepXouY/visitors/5LRVvbDTF5gJb757KIm5g
Content-Type: application/json
