GET http://localhost:3001/bulletins/pDfsD2woza9g8v1gICk1J/messages

###

POST http://localhost:3001/bulletins/VWZPWo0iHYWKNku7A9Js1/messages
Content-Type: application/json

{
  "authorId": "c06PwPZJPaVFJ5uwYsYbP",
  "name": "Brichi",
  "message": "Hello world!"
}

###

DELETE http://localhost:3001/bulletins/H1X5IFqg50o9NbnepXouY/messages/mZNvtMXzwehTBI_rOqi_5
